# permissions for end users to edit networkpolicies.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: networkpolicy-editor-role
rules:
- apiGroups:
  - networking.k7o.io
  resources:
  - networkpolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - networking.k7o.io
  resources:
  - networkpolicies/status
  verbs:
  - get
