apiVersion: networking.k7o.io/v1alpha1
kind: NetworkPolicy
metadata:
  name: networkpolicy-sample
spec:
  podSelector: {}
  egress:
    - to:
        - domain: api.github.com
      ports:
        - port: 443
