name: CI/CD

on:
  push:
    paths-ignore:
      - README.md
      - renovate.json
      - LICENSE
  pull_request:
  workflow_dispatch:

jobs:
  cicd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v1
        with:
          version: v1.31
      - uses: actions/setup-go@v2
        with:
          go-version: '1.15.1'
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - if: "!startsWith(github.ref, 'refs/tags/v')"
        uses: goreleaser/goreleaser-action@v2
        with:
          args: build --rm-dist --snapshot
      - if: startsWith(github.ref, 'refs/tags/v')
        uses: goreleaser/goreleaser-action@v2
        with:
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
